require("myluaconf.todo_comments")
require("myluaconf.telescope")
require("myluaconf.lualine")
require("myluaconf.compe")
require("myluaconf.treesitter")
require("myluaconf.lspconfig")
require("myluaconf.keymaps").init()
